-- INSERT INTO customer (customer_name, email, phone_number) VALUES
--                                                               ('Chukwuemeka Obi', 'chukwuemeka.obi@example.com', 08012345678),
--                                                               ('Aisha Bello', 'aisha.bello@example.com', 07012345678),
--                                                               ('Emeka Nwachukwu', 'emeka.nwachukwu@example.com', 09012345678),
--                                                               ('Ngozi Okafor', 'ngozi.okafor@example.com', 07023456789),
--                                                               ('Tunde Adeyemi', 'tunde.adeyemi@example.com', 08034567890);
